### ISSUE TITLE
Compiling problem can you help me?

### ISSUE THREAD

**Issue by ilnux4all** [ryancdotorg/brainflayer#112] opened 2020-05-07 21:16 UTC
hy when i do a make command this shows up:
_### **_gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainwalletio.o algo/warpwallet.o algo/keccak.o algo/sha3.o algo/brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lrt -lcrypto -lz -lgmp -o brainflayer
/usr/bin/ld: /tmp/brainflayer.wvUox1.ltrans0.ltrans.o: in function main': <artificial>:(.text.startup+0x21f5): undefined reference to bloom_chk_hash160'
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: brainflayer] Error 1_**_
i have tried a few things but im allready out of ideas
thank you for your help

**Comment by German-88** [comment] 2020-05-07 22:59
![image](https://user-images.githubusercontent.com/64992650/81352284-717a8280-90c6-11ea-82bd-a35a882c5f9c.png)

i have the same error. Does anyone know the cause? Thanks

**Comment by Yeicov** [comment] 2020-05-21 06:45
> hy when i do a make command this shows up:
> _### **_gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainwalletio.o algo/warpwallet.o algo/keccak.o algo/sha3.o algo/brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lrt -lcrypto -lz -lgmp -o brainflayer /usr/bin/ld: /tmp/brainflayer.wvUox1.ltrans0.ltrans.o: in function main': :(.text.startup+0x21f5): undefined reference to bloom_chk_hash160' collect2: error: ld returned 1 exit status make: *** [Makefile:68: brainflayer] Error 1_**_
> i have tried a few things but im allready out of ideas
> thank you for your help

Have you fixed the compilation error? I have tried some things but I don't succeed.

**Comment by ryancdotorg** [comment] 2020-05-21 08:50
Kali is not, and will not ever be a supported build platform.

This looks like an issue with GCC's linker

I'm hoping to have some time to update things in July.

**Comment by szarkos** [comment] 2020-07-17 23:32
As a quick fix you could edit bloom.h and change the definition of bloom_chk_hash160() from inline to static. Not sure inline is buying much anyway, but you'd need to benchmark.

**Comment by dextronomous** [comment] 2020-07-24 19:46
removing the static, and the -lpthread made me compile after many many not compiling,
then what happens, and what other places, szarkos, thanks alot
worked for me

**Comment by IJMacD** [comment] 2020-09-16 06:11
Ran into same problem.

Fixed it by editing `bloom.h` @ line 38:

```diff
- inline unsigned int bloom_chk_hash160(unsigned char *bloom, uint32_t *h) {
+ static unsigned int bloom_chk_hash160(unsigned char *bloom, uint32_t *h) {
```

**Comment by lolsilent** [comment] 2020-09-21 00:49
with latest ubuntu and latest kali same problem here:

 make
gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainv2.o algo/brainwalletio.o algo/keccak.o algo/sha3.o algo/warpwallet.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -lgmp -lpthread -o brainflayer
/usr/bin/ld: /tmp/brainflayer.rsB4Yi.ltrans0.ltrans.o: in function `main':
<artificial>:(.text.startup+0x2265): undefined reference to `bloom_chk_hash160'
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: brainflayer] Error 1

**Comment by Rudamx** [comment] 2020-11-15 13:33
Who can help set up Brainflayer on Ubuntu?

**Comment by Alf71** [comment] 2020-11-23 11:23
![BF](https://user-images.githubusercontent.com/7470579/99949286-11ee7680-2d7b-11eb-9511-61cb03bc1399.png)

Use following commands (delete old folder of Brainflayer, if you already had installed it):

$ git clone https://github.com/matchv/brainflayer.git
$ apt-get install openssl
$ apt-get install libgmp3-dev
$ apt-get install libimobiledevice-dev libplist-dev libusbmuxd-dev libssl-dev zlib1g-dev
$ apt-get install dh-autoreconf
$ cd brainflayer/
$ make 


It works using Ubuntu (and probably also using Kali) in Windows and is the solution for:
"Makefile:68: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1"

**Comment by ryancdotorg** [comment] 2020-11-23 11:55
should be fixed now for modern ubuntu.

**Closed by ryancdotorg** 2020-11-23 11:55 UTC
